DefUsersTable:
        Type: AWS::DynamoDB::Table
        Properties:
                AttributeDefinitions:
                        - AttributeName: id
                          AttributeType: S
                        - AttributeName: email
                          AttributeType: S
                BillingMode: PAY_PER_REQUEST
                KeySchema:
                        - AttributeName: id
                          KeyType: HASH
                GlobalSecondaryIndexes:
                        - IndexName: search_email
                          KeySchema:
                                - AttributeName: email
                                  KeyType: HASH
                          Projection:
                                ProjectionType: KEYS_ONLY
                TableName: users
